### ISSUE TITLE
Missing translation vars

### ISSUE THREAD

**Issue by ptopenweb** [YJSGframework/yjsg#11]
There are several strings in YJSG template panel that doesn't have translation vars.
Some examples:
"YJSG Plugin Check"
"YJSG Plugin v2.1.3 is installed and published."
"Click here to manage this extension.
"Logo is disabled"
"Yes"/"No" buttons
"Enable"/"Disable" buttons
"Flexible" "In header" select boxes (and other select boxes)
"None selected"/"Deselect All" "Search"  "Select all"
"Square" "Round" "Blank"
"Select layout" 
"Your google code"
"Your description goes here"
"Your keywords goes here"

Also the plugin panel (in plugin manager) "System - Yjsg Framework" doesn't have translations vars

**Comment by danyj** [comment]
Reinstall the plugin please all langs  are there.
https://github.com/YJSGframework/yjsg/blob/master/language/en-GB.plg_system_yjsg.ini

**Comment by ptopenweb** [comment]
I'm sorry, but they aren't, if you check careful you will see.
Search for instance for "Square"... or many of the other i said before.

Also there is a string without "" in that file

**Comment by danyj** [comment]
@ptopenweb can you please point to the lang string that is missing closing ? 
I will look at the other issues you mentioned. I see now that you are talking about hard coded strings if you can point them out and please note that template also has lang strings like 

COM_TEMPLATES_YJSG_VERSION_CHECK_FIELDSET_LABEL="YJSG System Check"
YJSG_CHECK ="YJSG Plugin Check"
YJSG_CHECK_TIP="This template runs on YJ Simple Grid Template Framework. YJSG plugin is required for this template."
YJSG_INS_PUB="YJSG Plugin"
YJSG_INS_PUB2="is installed and published."
YJSG_UNPUB="YJSG Plugin is unpublished."
YJSG_UNINS="YJSG Template Framework Plugin is required for this template but it is not installed."
YJSG_PLUGIN_NOT_FOUND="This template requires <a href="http://www.yjsimplegrid.com" target="_blank">YJSG Template Framework Plugin</a> to be installed and published."
YJSC_PUB_EXT="Click here to publish this extension."
YJSC_MAN_EXT="Click here to manage this extension."

**Comment by danyj** [comment]
"None selected"/"Deselect All" "Search" "Select all"
"Flexible" "In header" select boxes (and other select boxes)

are js lang strings from jquery plugins which we tend to stay away from modifying

**Comment by danyj** [comment]
These 3 
"Your Google code"
"Your description goes here"
"Your keywords goes here"
are default options and joomla does not allow lang inside those 
aka  default="set as default"

**Comment by danyj** [comment]
We added several fixes for ys/no , enable /disable and few others.
Tomorrow we plan to release 2.2.0 so it would be nice if you can point to the missing lang closing before that.
