### ISSUE TITLE
Frontend edit: category list, not adding new article to chosen category

### ISSUE THREAD

**Issue by ptopenweb** [YJSGframework/yjsg#13]
I don´'t know if this is a problem in YJSG Frameqork or Exinium template but were it goes.

**Steps to reproduce the issue**
Create a menu item with category list, choose a category other than uncategorized.
In frontend edit, go to that category and user "New" to create an article in that category, add some text and save.

**Expected result**
Ths article should be same saved in the chosen category (the one the menu item points).

**Actual result**
Ths article is not saved in the chosen category.

**System information**
Joomla 3.3.6
YJSG 2.2.0
Eximium 1.0.0 template

**Additional comments**
Also there seems to be similiar problems with the languague combobox too (try in a multilangue setup).

**Comment by danyj** [comment]
In publishing tab you need to select your category
http://screencast.com/t/sydGOhJg5Sa 
It defaults to first category (which in Eximium demo is Latest)  as ordered in category manager
The add article does not assign the category automatically

**Comment by danyj** [comment]
will add this in for category assigemant

**Comment by ptopenweb** [comment]
Yes i know that, but even if i manually select (which core joomla doesn't need) it doesn't work.

Check the languague combobox too. I don't have the current languague selected and also the "All" doesn't appear

**Comment by danyj** [comment]
Here a screen 
http://screencast.com/t/LWHGiRsTJeA
works ok for me.

**Comment by danyj** [comment]
fix is up for this issue , download master and reinstall
