### ISSUE TITLE
[feature] Replace squezebox for jquery alternative in shortcodes call

### ISSUE THREAD

**Issue by ptopenweb** [YJSGframework/yjsg#20]
Since, for my understanding, mootools will be deprecated from joomla in the future, suggestion to replace Squeezebox in the shortcodes call for other jquery alternative.

Example: http://fancyapps.com/fancybox/ 
This one seems to be very good with good documentaion too (lot of options, events and callbacks), and can be easily translated using "tpl" option (no core changes).
Or just bootstrap modals

**Comment by danyj** [comment]
On that one we must follow joomla , what ever they decide to use as admin lightbox is what we will use. So for now it is Squeezebox .

**Comment by ptopenweb** [comment]
yes, true. you're right is better always to use core functions.

**Comment by ptopenweb** [comment]
Sorry to reopen, but don't forget the shotcodes also exist in frontend edit.

**Comment by danyj** [comment]
same thing bud , we cant mix and mach between front and back and if we have to use another one we would use ours, magnific popup

**Comment by ptopenweb** [comment]
ok. thanks for the info
