### ISSUE TITLE
Shortcodes templates ready for extend and translations

### ISSUE THREAD

**Issue by danyj** [YJSGframework/yjsg#25]
OK , we have converted shortcodes to php files. 
You can now extend them with php and add anything you require in them,

@ptopenweb this is ready for you if you like to contribute further for lang strings translations.

**Comment by ptopenweb** [comment]
danyj did you see my comment on this commit?
https://github.com/YJSGframework/yjsg/commit/430b96b7731865d84a0348100684f191e3454b12#commitcomment-9567839

**Comment by ptopenweb** [comment]
PR https://github.com/YJSGframework/yjsg/pull/27
Please note that js vars still not in PR
Read my previous comment

**Comment by danyj** [comment]
Yes yes , I saw the comment and will have those moved to inline. Doing it now and will push new php files.

**Comment by ptopenweb** [comment]
oh already done that

**Comment by ptopenweb** [comment]
check here https://github.com/ptopenweb/yjsg/commits/master

**Comment by danyj** [comment]
oh , no no , should not have done it that way 
only the lang strings will be added to php
at the bottom of the shortcodes files

**Comment by ptopenweb** [comment]
ok so do it.

**Comment by danyj** [comment]
on it now. lucky that the 27 did not had those just the string. no prob, I am on this. 
thnx

**Comment by danyj** [comment]
all done, will have guys test it.

**Comment by ptopenweb** [comment]
hum, i noticed now that there is still one point missing for finalizing shortcodes translations:
The button names in shortcodes.js
There are already lang vars for them they are 'YJSG_SHORTCODES_*_NAME'.
Maybe it's needed js again in yjsg_head.php files for this

**Comment by mikimaus144** [comment]
it works fine, no bugs, everything is ok.

**Comment by Wasah** [comment]
Tested on joomla 3 , all fine.

**Comment by danyj** [comment]
@ptopenweb 
"hum, i noticed now that there is still one point missing for finalizing shortcodes translations"
how are you going to translate , media shortcodes, icons shortcodes etc, they seem like globals to me

**Comment by danyj** [comment]
@ptopenweb you are talking about those 
http://screencast.com/t/4hg5xML7bIV
right?

**Comment by ptopenweb** [comment]
yes

**Comment by danyj** [comment]
I really would not touch those , those are global words, I do not see
any benefit from trying to translate them. But if you guys think that is a benefit than it should be added here https://github.com/YJSGframework/yjsg/blob/master/yjsg.php#L1050

**Comment by ptopenweb** [comment]
danyj, in translation there is no such thing as a global word :)
imagine, for instance, greek, russian, arabic, chinese, etc
in our case we have portuguese content editors (no IT personal) that will use it. Knowing english is not a pre-requisite.
That's why we need all strings translated, especially frontend and frontend edition.
I can imagine a lot of cases like that.

If we do that change can i PR to main master?
As you can understand, we don't want to change the core of yjsg and them lose the changes at each update.

**Comment by danyj** [comment]
ok go ahead, you wont loose changes, those strings
https://github.com/YJSGframework/yjsg/blob/master/yjsg.php#L1050
 will get outputted in html head and are required for shortcodes to work, so adding 5 more for buttons is not a big deal .  Send pt il look over and merge.

**Comment by danyj** [comment]
In meantime I am on eximium repos and translations

**Comment by ptopenweb** [comment]
ok close this ticket, i now have other things to do, when i have time i will do that
thanks!

And cool for eximium! I will check that too when i have time.

**Comment by danyj** [comment]
just follow the string 

jstr_button_media
jstr_button_icons ...

**Comment by ptopenweb** [comment]
ok

**Comment by ptopenweb** [comment]
Hi danyj i think about the shortcodes and putted up in a branch of ours a new working method for them, that i think can simplify the shortcodes. It uses json files

See were, read the comments, and tell me what you guys think
https://github.com/ptopenweb/yjsg/commit/0f4830a57aa17b7cd4ed38bd54a4dda8b8f32ecc
