### ISSUE TITLE
[Joomla! 3.5.0-beta2] Fatal error: Class 'YjsgJDocumentHTMLDefault' not found

### ISSUE THREAD

**Issue by DonMartin** [YJSGframework/yjsg#29]
Hi!, I am testing Eximium on J3.5.0 beta 2, while this template and Framework works fine in frontend but in backend when i go to edit style in Template Manager, the next displayed is an error

`Fatal error: Class 'YjsgJDocumentHTMLDefault' not found in [root]/plugins/system/yjsg/includes/yjsgcore/classes/extend/30/html/html.php on line 20`

Template version: 1.0.0
YJSG plugin version: 2.2.2

**Comment by danyj** [comment]
Thnx for reporting , we are keeping an eye on it , there are few more issues with 3.5 that need to be resolved .  https://github.com/joomla/joomla-cms/issues/8963

But I cannot confirm this ,  there are no errors 

http://screencast.com/t/tjiWcXud8Szb

an you please advise how you got the errors , what was the install/upgrade process

**Comment by danyj** [comment]
I also checked the classes creation process and it works fine on my end , 
please make sure that 
 
    /plugins/system/yjsg/includes/yjsgcore/classes/

folder is writable, otherwise classes cannot be copied over

**Comment by IvanovAntonP94** [comment]
Hi, i have the same problem.
YJSG v2.0.0
Businessreport  template
Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT

**Comment by danyj** [comment]
@IvanovAntonP94    lates yjsg v is 2.2.3  https://github.com/YJSGframework/yjsg/releases/tag/2.2.3

please update and check

**Comment by IvanovAntonP94** [comment]
@danyj
Thank you
