### ISSUE TITLE
accordion menu

### ISSUE THREAD

**Issue by dsimonse** [YJSGframework/yjsg#30]
I want to use the accordion menu but it's not perfect :)
I want to use at least a 3-tier menu but with the "accordion no toggle" option the menu becomes to long and with the "accordion" option the menu closes to level1 all the time.
I would like it to be like this: I select a level1 menu option wich opens up several level2 option. I select a level 2-option that opens up several level-3 options wich are the final selectable options.
If I want to open another level2 option the previous level2 should close and my new selection should open.
![menu-less expanded](https://cloud.githubusercontent.com/assets/17233634/13033950/e485c75a-d327-11e5-9e42-e7be13b2f23b.PNG)
![menu-expanded](https://cloud.githubusercontent.com/assets/17233634/13033951/e67ecfe8-d327-11e5-9f54-9da6c76b4b36.PNG)

**Comment by danyj** [comment]
Not sure what the problem is , here is video with all levels 
http://screencast.com/t/DG6i5EsDi

http://prntscr.com/a34h05

**Comment by dsimonse** [comment]
Hi Dan! The video shows how I want it to work but it doesn't.
It's our new site so it isn't published yet - but you have selected "accordion"?

http://rojteatern.nu/nysite15/

**Comment by danyj** [comment]
yes , I have accordion selected

**Comment by dsimonse** [comment]
Ok - me too - but I get a different behaviour than you showed.

**Comment by danyj** [comment]
ok I was able to replicate the issue , and is happening only when menu is in offcanvas position , inspecting

**Comment by dsimonse** [comment]
That's great that you were able to reproduce it!

**Comment by danyj** [comment]
this seems like expected behavior , 

Accordion option should toggle next level and works only 1 level deep , 
no toggle should do what you need and it shows only first level drops, can you please switch to no toggle


previous msg about offcanvas  was wrong since I had 2 menus published , one on page , another in offcanvas

**Comment by danyj** [comment]
Here is new video with template you have . the accordion setting and the switch to no toggle 
http://screencast.com/t/LffJPbFBi

**Comment by dsimonse** [comment]
Hi Dan,
So is it possible to have it as a enhancement-request?

**Comment by danyj** [comment]
I cannot promise it , did try to make it work as you asked today but the structure is to complex to close only the ones that belong to an open sub . This is why we did the double option instead.

**Comment by dsimonse** [comment]
So what's the difference in the code in the first video where you showed that it worked in a vertical menu?

**Comment by danyj** [comment]
it did not work , there were 2 menus , and it was closing the "hidden" one ( offcanvas)  and opening visible one, when I disabled it it acted by default
