### ISSUE TITLE
YJSG prevents Joomla from showing punctuation marks in meta description

### ISSUE THREAD

**Issue by tjaafar** [YJSGframework/yjsg#31]
When using any of Eximium templates, it removes the punctuation marks from the "meta description" (except the "!").

I found that I need to edit this file "yjsg.php" (located in your_joomla_folder\plugins\system\yjsg). Under the function "onBeforeRender", you must remove the call to "yjsg_clean_shortcodes".

Please refer to this link on StackOverflow: http://stackoverflow.com/questions/36171584/joomla-is-not-showing-punctuation-marks-in-meta-description

**Comment by danyj** [comment]
@tjaafar  do not edit framework main files, 

https://github.com/YJSGframework/yjsg/blob/e43be49543e6b15ca537373ed1e14f69d003299d/includes/yjsgshortcodes/yjsg_shortcodes.php#L690

is there to cleanup strings from shortcode tags .  Please advise where and how to test.

**Comment by danyj** [comment]
I added this in template index.php


    $document->setMetaData("description", "This is, just, a sample meta description! Good luck.");


and that is exactly what I got out 
http://prntscr.com/arwocv
