### ISSUE TITLE
Problems with yjsg framework

### ISSUE THREAD

**Issue by SaidBa** [YJSGframework/yjsg#33]
What I found out is when you press submit the new event, some where trigger it reset our the Easysocial table #__social_step_sessions `STEP` columns to 0 based on your current session id.

So that the Easysocial system detected the event current step value is 0, then it throw out this error message Unable to detect session.

see the link: http://screencast.com/t/aGJ6pOyp

Please advice en give solution

**Comment by danyj** [comment]
yjsg is not touching the database or sessions. 
you might want to post in Easysocial forums

**Comment by SaidBa** [comment]
i did en this is what they said

**Comment by SaidBa** [comment]
is there a solution for it, because i still have the problem

**Comment by danyj** [comment]
@SaidBa   we have not encounter issues with easy social , give more details on how to reproduce the problem. how is event created , where ( admin/front ) , joomla versions , easy social versions, possible demo of the bug

**Comment by SaidBa** [comment]
1. Create a new event and the error will appear. username Pablo en password: mama123
2. If you change to Joomla default 'Protostar' template and create an event it will work fine.
I have included a sample screenshot of the database social_step_sessions table that may explain the behind the scenes of how this issue is occurring. 

http://screencast.com/t/dispQfIT

Please advice

**Comment by SaidBa** [comment]
[Not possible to create a event, it gives error.pdf](https://github.com/YJSGframework/yjsg/files/338645/Not.possible.to.create.a.event.it.gives.error.pdf)

As you can see in the file, this is what they told me. So please advice

**Comment by danyj** [comment]
@SaidBa    you referenced username and pass but what website ?

**Comment by danyj** [comment]
I just tested event creation on your site and is impossible that yjsg is doing anything , 
we have no overrides for easy social , 
https://github.com/YJSGframework/yjsg/tree/master/includes/html

yjsg is not touching the DB or components, 
and the bug is session related which again has nothing to do with the template, 
their form for events http://prntscr.com/bmgvwf

is not default edit form which I have assumed that might be the cause


in meantime while I test on local , please list all 3rd party extensions and plugins you have installed besides our template and yjsg

**Comment by danyj** [comment]
@SaidBa  I tested latest Easysocial with eximium and yjsg 2.2.3 , 
http://take.ms/QBjRB
and in timeline event creation works as it should 
but I cant find the way to add that button on the left side that you have to create event

let me know how to enable that so I cant test more

**Comment by SaidBa** [comment]
set up a menu en link that to events from easysocial

**Comment by danyj** [comment]
No issues at all , as previously said , yjsg cant affect it 

http://take.ms/fMDvX

just becuase someone  on their forum switched template does not mean that is yjsg fault,
