### ISSUE TITLE
Problems with yjsg framework

### ISSUE THREAD

**Issue by SaidBa** [YJSGframework/yjsg#34]
See att

[Not possible to create a event, it gives error.pdf](https://github.com/YJSGframework/yjsg/files/338648/Not.possible.to.create.a.event.it.gives.error.pdf)

**Comment by SaidBa** [comment]
to understand the problem, see screenshot: http://screencast.com/t/aGJ6pOyp

**Comment by danyj** [comment]
please do not open several threads for same issue. continue here 
https://github.com/YJSGframework/yjsg/issues/33
