### ISSUE TITLE
Print icon missing

### ISSUE THREAD

**Issue by pionir** [YJSGframework/yjsg#35]
I was working around with the plugin and I found out that the print icon is missing when bootstrap is off.
This is the fix for it.

All instances of this:

```
if (!$this->print){
	$print_icon = JHtml::_('icon.print_popup', $this->item, $params);
}else{
	$print_icon = JHtml::_('icon.print_screen', $this->item, $params);
	
}
```

needs to be changed to this

`$print_icon = JHtml::_('icon.print_screen', $this->item, $params);`

**Comment by danyj** [comment]
Submit pull request please and we will look over. Thnx!
