### ISSUE TITLE
Module Off does not work for sub pages.

### ISSUE THREAD

**Issue by MrPJ1751** [YJSGframework/yjsg#39]
The Template errors after updating the YJSJ Plugin.
The Original Demo with data has Frame work 2.2.5
http://joomlatemplates.youjoomla.info/bizbiz/

When I add the template and the current framework to my site.
The modules from the home page display when links are clicked from the home page.
Specifically... Under Board of directors on thee home page.
Click the photo Cindy Crautch. 
On the demo on your site and when I use the demo package all works excellent.  
but when I do this on mysite it fails to turn off the modules and the content is berried under all the modules that should not show from the home page.

I thought maybe there is a conflict with the current site and plugins or site components. 
I put the demo template here:
http://bizbiz.tcpirate.com/ 
It worked great. As expected.
If I update the plugin to the current version for download.
I get unexpected display issues where he template home page does not turn off the modules.

I reinstalled the original demo pack, and will look at all the settings in the YJSJ to confirm they are identical to my test site where this page does not preform as expected.
http://mcc.tcpirate.com/index.php?option=com_content&view=featured&Itemid=131
I have been turning on and off setings, and have already went page by page in global configuration ensuring the all the settings are correct. 

To reproduce the error install bizbiz demo and then install the current YJSJ frame work 2.2.5 and it will not function correctly. 

Thank you.

**Comment by danyj** [comment]
We tested latest Joomla and plugin no issues , https://monosnap.com/file/ZjBQk3phYUwyF4B0Fm7jebmcPzmlWh

since this is not plugin related issue please continue on Youjoomla support tickets or forums 

http://www.youjoomla.com/tickets
http://www.youjoomla.com/joomla_support
