### ISSUE TITLE
problem with registration form in template portofisimo

### ISSUE THREAD

**Issue by oblifund** [YJSGframework/yjsg#40]
what can i do about the following

it is not possible to display Joomla profile fields on registration form of Portfisimo template.

this is what my help whas emailing me
I found the problem. It is a problem with the template, especial its plugin System - Yjsg Framework

I had to edit its file default.php to show the fields. That plugin resets the form fields and does not include profile and custom fields.

**Comment by danyj** [comment]
Be precise please , what default.php what profile and what did you had to change ?

**Comment by oblifund** [comment]
I commented line 16 in that file /plugins/system/yjsg/legacy/html/com_users/registration/default.php

    $this->form->reset( true );

**Comment by oblifund** [comment]
from the template portifisimo what i use for the website

**Comment by danyj** [comment]
do not edit plugin files , 
do override in your template 

`templates/templatename/html/com_users/registration/default.php`

still need to know what profile you are talking about

**Comment by oblifund** [comment]
registration profile from  my website

**Comment by oblifund** [comment]
where can i override it

**Comment by oblifund** [comment]
http://www.oblifund.nl/registration this profile

**Comment by danyj** [comment]
copy this 

`/plugins/system/yjsg/legacy/html/com_users/registration/default.php
`

to 

`templates/templatename/html/com_users/registration/default.php`

and do what you need

**Comment by oblifund** [comment]
Tell him, it is not possible to show profile fields even you have enabled the plugin 'User - Profile'.
