### ISSUE TITLE
Probably more a wish than an issue...'

### ISSUE THREAD

**Issue by amiellasse** [YJSGframework/yjsg#42]
Hi pionir
Sorry, I'm far to be able to find the solution by myself...
Since your fix, we print directly the whole webpage instead of opening a _content_ print popup (using Joomla's "?tmpl=component" as I read somewhere)
Is there a way to fix the print icon, using this joomla's standard ?

**Comment by pionir** [comment]
Hi amiellasse.
I was checking this and you'r right. The popup_screen is printing the whole page. 
Try to do this, instead **print_screen** use **print_popup** and instead 

`$print_icon = preg_replace('/(>(.*?)<\/a>)/s', '><i class="fa fa-print"></i> <em>'.JText::_('JGLOBAL_PRINT').'</em></a>', $print_icon)`

use just:

`$print_icon`

Make the change in all of this files.
https://github.com/YJSGframework/yjsg/commit/3ef0bbed81b92831c050f88bd964e8043ce127d8

**Comment by amiellasse** [comment]
Hi All !
Sorry to open this again but I didn't yet try pionir's answer before danyj closed it.
I just changed back your 2.2.6 fix to 2.2.5 version before posting my first question and last Update (2.2.7) bring back my problem so i finally tested pionir's solution and it works now (thank you so much)

So I'm talking about changing back 2.2.6 fix to 2.2.5 version and just using 
$print_icon
Instead of
$print_icon = preg_replace('/(>(.*?)<\/a>)/s', '><i class="fa fa-print"></i> <em>'.JText::_('JGLOBAL_PRINT').'</em></a>', $print_icon)
in the 6 files

But I would like to know before you close this if you will apply your solution in next 2.2.8 version or if my problem is too specific.

Thank you again

**Comment by danyj** [comment]
this has been accepted in 2.2.8  and released

**Comment by danyj** [comment]
here , https://github.com/YJSGframework/yjsg/blob/master/includes/html/com_content/article/default.php#L18

**Comment by danyj** [comment]
last update was released 2 days ago https://github.com/YJSGframework/yjsg/releases/tag/2.2.8 , are you saying you have same issue again?

**Comment by amiellasse** [comment]
(...) I probably messed somewhere ^^'
I applied an update (sorry, it was the 2.2.8 and not 2.2.7 as I told before) found today in my Joomla's extension update manager and when I checked in front page, the print button opened directly the print settings.
I applied Pionir's solution on the 6 files by ftp and it worked...

I just checked now this 6 files in the dowloaded [Plugin_Yjsg_Framework-2-2-8.zip] and they don't have the Pionir's solution applied. 

I mean his 9 month ago fix is applied but not the 24 May solution

**Comment by amiellasse** [comment]
I exactly just checked the includes\html\com_content\article\default.php in the dowloaded [Plugin_Yjsg_Framework-2-2-8.zip]
