### ISSUE TITLE
Fatal error after update to Joomla 3.8.0

### ISSUE THREAD

**Issue by Michael-Hartmann1984** [YJSGframework/yjsg#43]
Fatal error: Class 'YjsgJViewLegacyDefault' not found in plugins/system/yjsg/includes/yjsgcore/classes/extend/30/component/view.php on line 21

**Comment by danyj** [comment]
Checking please wait

**Comment by danyj** [comment]
This will take a while,   joomla has decided to rearrange class names and folders jet again on a minor version change. We are working on a fix.

**Comment by Michael-Hartmann1984** [comment]
OK, thanks a lot. How long is while?

**Comment by danyj** [comment]
im on it right now, looking for moved files. cant give eta

**Comment by danyj** [comment]
got it to work , fixing minor issues now for BC ,
this is the issue ref 
https://github.com/joomla/joomla-cms/issues/17992#issuecomment-330697311

**Comment by danyj** [comment]
@Michael-Hartmann1984   https://github.com/YJSGframework/yjsg/releases/tag/2.2.9

download and reinstall please

**Comment by Michael-Hartmann1984** [comment]
Thanks a lot for your very fast fix.
