### ISSUE TITLE
YJSG Framework install error -  No operator matches the given name and argument type(s). You might need to add explicit type casts.

### ISSUE THREAD

**Issue by Ria-Doshi** [YJSGframework/yjsg#44]
We have a Joomla 3.8 instance on a Linux apache server, with a PostgreSQL Database. We were trying to use the Eximium template which installed successfully but the when I tried to install the YJSG framework plugin got the bellow error which brought down Joomla - "ERROR: operator does not exist: character varying = integer LINE 3: WHERE client_id = 0 AND a.home = 1 ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts."

Any suggestions on how to fix issue?

**Comment by danyj** [comment]
sorry but I have no way to test on PostgreSQL, note that YJSG is not doing anything to DB , so I would say is plugin install issue not YJSG adding to DB, try another plugin

**Comment by Ria-Doshi** [comment]
Other plugins have installed successfully.

**Comment by danyj** [comment]
any way to trace the error to a script?

>  not doing anything to DB 

I take that back,  there is one instance 
try commenting this out within the zip 


https://github.com/YJSGframework/yjsg/blob/master/install.script.php#L35-L56

that is the only DB script that I know off and it only sets the order
