### ISSUE TITLE
Read more not cutting of content in cat view

### ISSUE THREAD

**Issue by danyj** [YJSGframework/yjsg#45]
http://www.youjoomla.com/joomla_support/showthread.php?p=67324#post67324

**Comment by danyj** [comment]
@swemmel  sorry for moving you around , 

ok , I tested on my end and see no issues 

![screenshot_1](https://user-images.githubusercontent.com/2340172/32891616-9ab14956-cad3-11e7-9785-cfa257826775.jpg)


![screenshot_2](https://user-images.githubusercontent.com/2340172/32891620-9e353b14-cad3-11e7-9917-4c88c4bf6ff1.jpg)


will test with layout changes , 
untill than please change editor view to code view and copy paste the code here , let me test exactly what you have . 

Also advise if and what layout options have you changed so that I can test faster.

**Comment by danyj** [comment]
Also advise what plugins you have on , there might be some that kill the read more. 
On clean install with just YJSG  and YJ extensions I cant see this bug.

**Comment by swemmel** [comment]
Hello Neo,

You can close this one. I found the cause. It was a plugin that automattically put a readmore. I de-installed it and everything works fine right now. Sorry for the inconvenience.

Best regards,
Peter

**Comment by danyj** [comment]
OK , thnx!
