### ISSUE TITLE
"data-before" attribute doesn't work

### ISSUE THREAD

**Issue by netica** [YJSGframework/yjsg#47]
Hi, I have problem with "data-before" attribute. I have made sticky menu by adding specjal DIV:
<div class="yjsg-sticky" data-hide="no" data-pushed="0" data-offset="300" data-effect="slide" data-before="200"> ... </div>

But everytime you click on menu item it's scroll too low (below the header). I'v try to increse "data-before" but it doesn't work. Any idea what can be wrong?

Website address: http://ga.netica.pl/ 
Thank You in advance

**Comment by danyj** [comment]
`data-before` goes on `yjscroll `elements not the menu container as shown here
https://yjsimplegrid.com/add-ons/sticky.html

see this video

http://take.ms/hQ34b

add this in any JS file that goes after jQuery

```
        $(document).ready(function() {
			
			$('.yjsg-sticky .yjscroll').attr('data-before','200');

        });
```

**Comment by netica** [comment]
Thank You
