### ISSUE TITLE
Fatal Error was detected!

### ISSUE THREAD

**Issue by Rollmodl** [YJSGframework/yjsg#48]
After upgrading to Kunena, the forum is getting the following 500 Internal Server Error:

The error was detected in the System - Yjsg Plugin.

Fatal Error: Cannot declare class JPagination, because the name is already in use in plugins/system/yjsg/includes/yjsgcore/classes/extend/38/pagination/pagination.php on line 288

**Comment by danyj** [comment]
try moving their system plugin after YJSG .

**Comment by danyj** [comment]
> After upgrading to Kunena

give more details upgrading what version Joomla and  Kunena .

**Comment by Rollmodl** [comment]
Kunena 5.0.14
Joomla 3.8.8

**Comment by Rollmodl** [comment]
I edited my post and restored my site to the previous version.

**Comment by danyj** [comment]
im testing now

**Comment by danyj** [comment]
Upgraed ,  http://prntscr.com/jpoaef

http://prntscr.com/jpoalm

Joomla 3.8.8
Kunena 5.10
YJSG 2.3.2 

I even moved plugins order around http://prntscr.com/jpobuq

and no issues. 

Are you on latest YJSG ?

**Comment by Rollmodl** [comment]
YJSG v2.3.2

**Comment by danyj** [comment]
what other plugins/components do you have?

**Comment by Rollmodl** [comment]
Did you click on the topics?

**Comment by Rollmodl** [comment]
Try clicking on the topics. The forum shows but the error occur when a topic is selected.

**Comment by danyj** [comment]
Just did , 
http://prntscr.com/jpodr6

il test some more

**Comment by Rollmodl** [comment]
![2018-06-01_150422](https://user-images.githubusercontent.com/18010421/40861020-1c5a398a-65ad-11e8-8dd5-d776af058f88.jpg)

**Comment by danyj** [comment]
tested pagination , created few topics , clicked paging everything works 
http://prntscr.com/jpofdb


Only thing to try is move the order of YJSG plugin. I cant replicate the issue.

**Comment by Rollmodl** [comment]
Ok, thanks.

**Comment by danyj** [comment]
Just tested messages per page , everything works on my end. 
YJSG overrides Jpagination to add class names , 

this 
> Fatal Error: Cannot declare class JPagination, because the name is already in use in 

tells me that YJSG was to late to do so since something did it before, thus moving plugin order might help. Just try to set YJSG first or last
