### ISSUE TITLE
Questions about Eximium Demo for Joomla 3.x

### ISSUE THREAD

**Issue by kkae8989** [YJSGframework/yjsg#49]
Hello,
I used the "DEMO version of J3.X for Eximium Joomla Template" to make my website.
However, after the installation, the message "1146 __wf_profiles' doesn't exist" appears. I can't see the back page of JOOMLA. How can I solve it?

**Comment by danyj** [comment]
It is JCE , Il pacj new demo in a few

**Comment by danyj** [comment]
All set , removed JCE editor from the install. New demo is up . 
https://www.youjoomla.com/joomla-templates/eximium-free-joomla-template-powered-by-yjsg-v2.html

Thnx for advising.
